Waiting for build to start...
Picked Git content provider.
Cloning into '/tmp/repo2dockerf11kz5lt'...
HEAD is now at f3b5afb try, try again
Python version unspecified, using current default Python version 3.10. This will change in the future.Building conda environment for python=3.10
Using PythonBuildPack builder
#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 5.08kB done
#1 DONE 0.1s

#2 [internal] load metadata for docker.io/library/buildpack-deps:jammy
#2 DONE 0.4s

#3 [internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.1s

#4 [ 1/20] FROM docker.io/library/buildpack-deps:jammy@sha256:d4dd8c4891377f710f1509f5a3aa777e9d64f3c93f9b3be198a10cdd497c8ac4
#4 resolve docker.io/library/buildpack-deps:jammy@sha256:d4dd8c4891377f710f1509f5a3aa777e9d64f3c93f9b3be198a10cdd497c8ac4 0.1s done
#4 DONE 0.1s

#5 [internal] load build context
#5 transferring context: 79.33kB 0.0s done
#5 DONE 0.1s

#6 [ 5/20] RUN apt-get -qq update &&     apt-get -qq install --yes --no-install-recommends        gettext-base        less        unzip        > /dev/null &&     apt-get -qq purge &&     apt-get -qq clean &&     rm -rf /var/lib/apt/lists/*
#6 CACHED

#7 [ 2/20] RUN apt-get -qq update &&     apt-get -qq install --yes --no-install-recommends locales > /dev/null &&     apt-get -qq purge &&     apt-get -qq clean &&     rm -rf /var/lib/apt/lists/*
#7 CACHED

#8 [ 3/20] RUN echo "en_US.UTF-8 UTF-8" > /etc/locale.gen &&     locale-gen
#8 CACHED

#9 [ 4/20] RUN groupadd         --gid 1000         jovyan &&     useradd         --comment "Default user"         --create-home         --gid 1000         --no-log-init         --shell /bin/bash         --uid 1000         jovyan
#9 CACHED

#10 [ 6/20] COPY --chown=1000:1000 build_script_files/-2fopt-2fvenv-2flib-2fpython3-2e12-2fsite-2dpackages-2frepo2docker-2fbuildpacks-2fconda-2factivate-2dconda-2esh-e67d51 /etc/profile.d/activate-conda.sh
#10 CACHED

#11 [ 6/18] COPY --chown=1000:1000 build_script_files/-2fopt-2fvenv-2flib-2fpython3-2e12-2fsite-2dpackages-2frepo2docker-2fbuildpacks-2fconda-2factivate-2dconda-2esh-e67d51 /etc/profile.d/activate-conda.sh
#11 CACHED

#12 [ 7/18] COPY --chown=1000:1000 build_script_files/-2fopt-2fvenv-2flib-2fpython3-2e12-2fsite-2dpackages-2frepo2docker-2fbuildpacks-2fconda-2fenvironment-2epy-2d3-2e10-2dlinux-2d64-2elock-2bb6e8 /tmp/env/environment.lock
#12 CACHED

#13 [ 8/18] COPY --chown=1000:1000 build_script_files/-2fopt-2fvenv-2flib-2fpython3-2e12-2fsite-2dpackages-2frepo2docker-2fbuildpacks-2fconda-2finstall-2dbase-2denv-2ebash-637204 /tmp/install-base-env.bash
#13 CACHED

#14 [ 9/18] RUN TIMEFORMAT='time: %3R' bash -c 'time /tmp/install-base-env.bash' && rm -rf /tmp/install-base-env.bash /tmp/env
#14 CACHED

#15 [10/18] RUN mkdir -p /srv/npm && chown -R jovyan:jovyan /srv/npm
#15 CACHED

#16 [12/18] WORKDIR /home/jovyan
#16 CACHED

#17 [11/18] RUN if [ ! -d "/home/jovyan" ]; then         /usr/bin/install -o jovyan -g jovyan -d "/home/jovyan";     fi
#17 CACHED

#18 [13/18] RUN chown jovyan:jovyan /home/jovyan
#18 CACHED

#19 [14/18] COPY --chown=1000:1000 src/requirements.txt /home/jovyan/requirements.txt
#19 DONE 0.3s

#20 [15/18] RUN /srv/conda/envs/notebook/bin/pip install --no-cache-dir -r "requirements.txt"
#20 0.852 Collecting ipykernel==5.3.4 (from -r requirements.txt (line 2))
#20 0.915   Downloading ipykernel-5.3.4-py3-none-any.whl.metadata (1.0 kB)
#20 0.968 Collecting ipython==7.18.1 (from -r requirements.txt (line 3))
#20 0.977   Downloading ipython-7.18.1-py3-none-any.whl.metadata (4.4 kB)
#20 0.993 Collecting ipython-genutils==0.2.0 (from -r requirements.txt (line 4))
#20 1.000   Downloading ipython_genutils-0.2.0-py2.py3-none-any.whl.metadata (755 bytes)
#20 1.021 Collecting ipywidgets==7.5.1 (from -r requirements.txt (line 5))
#20 1.029   Downloading ipywidgets-7.5.1-py2.py3-none-any.whl.metadata (1.8 kB)
#20 1.170 Collecting numpy==1.19.2 (from -r requirements.txt (line 6))
#20 1.180   Downloading numpy-1.19.2.zip (7.3 MB)
#20 1.300      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.3/7.3 MB 68.2 MB/s eta 0:00:00
#20 1.546   Installing build dependencies: started
#20 3.369   Installing build dependencies: finished with status 'done'
#20 3.372   Getting requirements to build wheel: started
#20 3.574   Getting requirements to build wheel: finished with status 'done'
#20 3.577   Preparing metadata (pyproject.toml): started
#20 4.471   Preparing metadata (pyproject.toml): finished with status 'error'
#20 4.481   error: subprocess-exited-with-error
#20 4.481   
#20 4.481   × Preparing metadata (pyproject.toml) did not run successfully.
#20 4.481   │ exit code: 1
#20 4.481   ╰─> [54 lines of output]
#20 4.481       Running from numpy source directory.
#20 4.481       setup.py:470: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
#20 4.481         run_build = parse_setuppy_commands()
#20 4.481       
#20 4.481       Error compiling Cython file:
#20 4.481       ------------------------------------------------------------
#20 4.481       ...
#20 4.481               for i in range(1, RK_STATE_LEN):
#20 4.481                   self.rng_state.key[i] = val[i]
#20 4.481               self.rng_state.pos = i
#20 4.481       
#20 4.481               self._bitgen.state = &self.rng_state
#20 4.481               self._bitgen.next_uint64 = &mt19937_uint64
#20 4.481                                          ^
#20 4.481       ------------------------------------------------------------
#20 4.481       
#20 4.481       _mt19937.pyx:138:35: Cannot assign type 'uint64_t (*)(void *) except? -1 nogil' to 'uint64_t (*)(void *) noexcept nogil'. Exception values are incompatible. Suggest adding 'noexcept' to the type of the value being assigned.
#20 4.481       Processing numpy/random/_bounded_integers.pxd.in
#20 4.481       Processing numpy/random/_mt19937.pyx
#20 4.481       Traceback (most recent call last):
#20 4.481         File "/tmp/pip-install-3lwb0060/numpy_5bd86990e5424280bb3f1893a463d8e3/tools/cythonize.py", line 235, in <module>
#20 4.481           main()
#20 4.481         File "/tmp/pip-install-3lwb0060/numpy_5bd86990e5424280bb3f1893a463d8e3/tools/cythonize.py", line 231, in main
#20 4.481           find_process_files(root_dir)
#20 4.481         File "/tmp/pip-install-3lwb0060/numpy_5bd86990e5424280bb3f1893a463d8e3/tools/cythonize.py", line 222, in find_process_files
#20 4.481           process(root_dir, fromfile, tofile, function, hash_db)
#20 4.481         File "/tmp/pip-install-3lwb0060/numpy_5bd86990e5424280bb3f1893a463d8e3/tools/cythonize.py", line 188, in process
#20 4.481           processor_function(fromfile, tofile)
#20 4.481         File "/tmp/pip-install-3lwb0060/numpy_5bd86990e5424280bb3f1893a463d8e3/tools/cythonize.py", line 77, in process_pyx
#20 4.481           subprocess.check_call(
#20 4.481         File "/srv/conda/envs/notebook/lib/python3.10/subprocess.py", line 369, in check_call
#20 4.481           raise CalledProcessError(retcode, cmd)
#20 4.481       subprocess.CalledProcessError: Command '['/srv/conda/envs/notebook/bin/python3.10', '-m', 'cython', '-3', '--fast-fail', '-o', '_mt19937.c', '_mt19937.pyx']' returned non-zero exit status 1.
#20 4.481       Cythonizing sources
#20 4.481       Traceback (most recent call last):
#20 4.481         File "/srv/conda/envs/notebook/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 389, in <module>
#20 4.481           main()
#20 4.481         File "/srv/conda/envs/notebook/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 373, in main
#20 4.481           json_out["return_val"] = hook(**hook_input["kwargs"])
#20 4.481         File "/srv/conda/envs/notebook/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 175, in prepare_metadata_for_build_wheel
#20 4.481           return hook(metadata_directory, config_settings)
#20 4.481         File "/tmp/pip-build-env-7limdvr2/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 157, in prepare_metadata_for_build_wheel
#20 4.481           self.run_setup()
#20 4.481         File "/tmp/pip-build-env-7limdvr2/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 248, in run_setup
#20 4.481           super(_BuildMetaLegacyBackend,
#20 4.481         File "/tmp/pip-build-env-7limdvr2/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 142, in run_setup
#20 4.481           exec(compile(code, __file__, 'exec'), locals())
#20 4.481         File "setup.py", line 499, in <module>
#20 4.481           setup_package()
#20 4.481         File "setup.py", line 479, in setup_package
#20 4.481           generate_cython()
#20 4.481         File "setup.py", line 274, in generate_cython
#20 4.481           raise RuntimeError("Running cythonize failed!")
#20 4.481       RuntimeError: Running cythonize failed!
#20 4.481       [end of output]
#20 4.481   
#20 4.481   note: This error originates from a subprocess, and is likely not a problem with pip.
#20 4.571 error: metadata-generation-failed
#20 4.571 
#20 4.571 × Encountered error while generating package metadata.
#20 4.571 ╰─> See above for output.
#20 4.571 
#20 4.571 note: This is an issue with the package mentioned above, not pip.
#20 4.571 hint: See above for details.
#20 ERROR: process "/bin/sh -c ${KERNEL_PYTHON_PREFIX}/bin/pip install --no-cache-dir -r \"requirements.txt\"" did not complete successfully: exit code: 1
------
 > [15/18] RUN /srv/conda/envs/notebook/bin/pip install --no-cache-dir -r "requirements.txt":
4.481       [end of output]
4.481   
4.481   note: This error originates from a subprocess, and is likely not a problem with pip.
4.571 error: metadata-generation-failed
4.571 
4.571 × Encountered error while generating package metadata.
4.571 ╰─> See above for output.
4.571 
4.571 note: This is an issue with the package mentioned above, not pip.
4.571 hint: See above for details.
------
Dockerfile:118
--------------------
 116 |     COPY --chown=1000:1000 src/requirements.txt ${REPO_DIR}/requirements.txt
 117 |     USER ${NB_USER}
 118 | >>> RUN ${KERNEL_PYTHON_PREFIX}/bin/pip install --no-cache-dir -r "requirements.txt"
 119 |     
 120 |     # ensure root user after preassemble scripts
--------------------
ERROR: failed to solve: process "/bin/sh -c ${KERNEL_PYTHON_PREFIX}/bin/pip install --no-cache-dir -r \"requirements.txt\"" did not complete successfully: exit code: 1
Error during build: Command '['docker', 'buildx', 'build', '--progress', 'plain', '--push', '--build-arg', 'NB_USER=jovyan', '--build-arg', 'NB_UID=1000', '--tag', 'registry.2i2c.mybinder.org/i-claycampaigne-2dhypercubes-848870:f3b5afbb1e75b0e4b6d0aa1ad6bedb6fc141f287', '--platform', 'linux/amd64', '/tmp/tmp5ifmd4qt']' returned non-zero exit status 1.Error in event stream: Error